### ISSUE TITLE
requireしなくてもよいライブラリを列挙するcopなかったっけ

### ISSUE THREAD

**Issue by pocke** [pocke/zatsu#7]
https://pocke.hatenablog.com/entry/2019/07/31/113053

**Comment by koic** [comment]
`Lint/UnneededRequireStatement` cop でしょうか？

**Comment by pocke** [comment]
ですです。stringioが含まれていたら対応する必要があるかなと思ったのですが、stringioは対象ではないみたいなので特に対応は必要なさそうですね。
